### ISSUE TITLE
Implement Touch ID

### ISSUE THREAD

**Issue by TomForus** [teamforus/concept-identity#8] opened 2018-03-08 11:13 UTC
# Implement Touch ID
## Sort of Issue

Enhancement

## Prerequisites

1. A log-in functionality on the native iOS ME-application
2. Done research about touch-id

## Description

This issue has been made to gain a biometric acces with your own unique fingerprint on the IOS MEapp. 

## Functional Design (Enhancement)

1. The steps of the functional design will be clear after the research is finished about the touch-id.

**User Story:** The person using the application has the possibility to log in the application via scanning his fingerprint. After the person has scanned it's fingerprint he or she gains acces to the IOS ME application.

**Comment by jamalv** [comment] 2018-03-13 07:01
duplicate of https://github.com/teamforus/concept-identity/issues/7

**Closed by jamalv** 2018-03-13 07:01 UTC
Labels: enhancement, iOS Native
