### ISSUE TITLE
Implementation of the design on the MEapp on Android

### ISSUE THREAD

**Issue by TomForus** [teamforus/concept-identity#11] opened 2018-03-08 12:53 UTC
# Implementation of the design on the MEapp on Android

## Sort of Issue

Enhancement

## Prerequisites

1. Finish the functionality of the native Anroid MEapp
2. Finish the designs of the  native Android MEapp

## Description

The implementation of the new designs made by @danrminds and @dev-weget in the native Android ME application made by @martijndoornik 

## Functional Design (Enhancement)

1. Insert ME-view (home-screen)
2. Insert Wallet-view
3. Insert records-view
4. Insert new-users views

**User Story:** The new designs of the MEapp should be fully functional on the native Android MEapp

**Comment by jamalv** [comment] 2018-03-13 06:23
Duplicate of https://github.com/teamforus/concept-identity/issues/10

**Closed by jamalv** 2018-03-13 06:23 UTC
Labels: Android Native, enhancement
